import os, sys


BASE_DIR = os.path.dirname(os.path.realpath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")

# ------------------------------------------------------------------------------------------ #
# 		CLI
# ------------------------------------------------------------------------------------------ #

STATIC_ANALYZER_CLI_DRIVER_PATH = os.path.join(os.path.join(BASE_DIR, "engine"), "cli.js")


# ------------------------------------------------------------------------------------------ #
# 		Tool-output Config
# ------------------------------------------------------------------------------------------ #

# local arguments tag for functions
LOCAL_ARGUMENT_TAG_FOR_FUNC = 'LOCAL_FUNCTION_ARGUMENT'
FUNCTION_CALL_DEFINITION_BODY = '<< FUNCTION_CALL_DEFINITION >>'
# esprima program node
PROGRAM_NODE_INDEX = '1'
WINDOW_GLOBAL_OBJECT = 'window [GlobalWindowObject]'
MAX_RECURSE = 100
outputCSVDelimiter = '¿'



# ------------------------------------------------------------------------------------------ #
# 	JavaScript Constants
# ------------------------------------------------------------------------------------------ #

# inline event names
JS_EVENT_NAMES = [
	"abort",
	"afterprint",
	"animationend",
	"animationiteration",
	"animationstart",
	"beforeprint",
	"beforeunload",
	"blur",
	"canplay",
	"canplaythrough",
	"change",
	"click",
	"contextmenu",
	"copy",
	"cut",
	"dblclick",
	"drag",
	"dragend",
	"dragenter",
	"dragleave",
	"dragover",
	"dragstart",
	"drop",
	"durationchange",
	"ended",
	"error",
	"focus",
	"focusin",
	"focusout",
	"fullscreenchange",
	"fullscreenerror",
	"hashchange",
	"input",
	"invalid",
	"keydown",
	"keypress",
	"keyup",
	"load",
	"loadeddata",
	"loadedmetadata",
	"loadstart",
	"message",
	"mousedown",
	"mouseenter",
	"mouseleave",
	"mousemove",
	"mouseover",
	"mouseout",
	"mouseup",
	"mousewheel",
	"offline",
	"online",
	"open",
	"pagehide",
	"pageshow",
	"paste",
	"pause",
	"play",
	"playing",
	"popstate",
	"progress",
	"ratechange",
	"resize",
	"reset",
	"scroll",
	"search",
	"seeked",
	"seeking",
	"select",
	"show",
	"stalled",
	"storage",
	"submit",
	"suspend",
	"timeupdate",
	"toggle",
	"touchcancel",
	"touchend",
	"touchmove",
	"touchstart",
	"transitionend",
	"unload",
	"volumechange",
	"waiting",
	"wheel"
]


JS_DEFINED_VARS = list(set([
	'window',
	'document',
	'localStorage',
	'sessionStorage',
	'indexOf',
	'toUpperCase',
	'toLowerCase',
	'substr',
	'jQuery',
	'hasOwnProperty',
	'push',
	
	# Value Properties
	"Infinity",
	"NaN",
	"undefined",
	"globalThis",

	# Function Properties
	"eval",
	"uneval ",
	"isFinite",
	"isNaN",
	"parseFloat",
	"parseInt",
	"decodeURI",
	"decodeURIComponent",
	"encodeURI",
	"encodeURIComponent",
	"escape",
	"unescape",
	"Object",
	"Function",
	"Boolean",
	"Symbol",
	"Error",
	"AggregateError ",
	"EvalError",
	"InternalError ",
	"RangeError",
	"ReferenceError",
	"SyntaxError",
	"TypeError",
	"URIError",
	"Number",
	"BigInt",
	"Math",
	"Date",
	"Array",
	"Int8Array",
	"Uint8Array",
	"Uint8ClampedArray",
	"Int16Array",
	"Uint16Array",
	"Int32Array",
	"Uint32Array",
	"Float32Array",
	"Float64Array",
	"BigInt64Array",
	"BigUint64Array",
	"Map",
	"Set",
	"WeakMap",
	"WeakSet",
	"ArrayBuffer",
	"SharedArrayBuffer ",
	"Atomics ",
	"DataView",
	"JSON",
	"Promise",
	"Generator",
	"GeneratorFunction",
	"AsyncFunction",
	"Iterator ",
	"AsyncIterator ",
	"Reflect",
	"Proxy",
	"Intl",
	"Collator",
	"DateTimeFormat",
	"ListFormat",
	"NumberFormat",
	"PluralRules",
	"RelativeTimeFormat",
	"Locale",
	"WebAssembly",
	"WebAssembly.Module",
	"WebAssembly.Instance",
	"WebAssembly.Memory",
	"WebAssembly.Table",
	"WebAssembly.CompileError",
	"WebAssembly.LinkError",
	"WebAssembly.RuntimeError",
	"Module",
	"Instance",
	"Memory",
	"Table",
	"CompileError",
	"LinkError",
	"RuntimeError",
	"arguments",
	"constructor",
	"toExponential",
	"toFixed",
	"toLocaleString",

	# Constructor Properties
	"Object",
	"Function",
	"Array",
	"ArrayBuffer",
	"String",
	"Boolean",
	"Number",
	"DataView",
	"Date",
	"Promise",
	"RegExp",
	"Map",
	"WeakMap",
	"Set",
	"WeakSet",
	"SharedArrayBuffer",
	"Symbol",
	"Error",
	"EvalError",
	"RangeError",
	"ReferenceError",
	"SyntaxError",
	"TypeError",
	"URIError"

	# Other Properties
	"Atomics",
	"Math",
	"JSON",
	"Reflect",
	"Proxy",

	# Object Constructor Function Properties
	"getPrototypeOf",
	"setPrototypeOf",
	"getOwnPropertyDescriptor",
	"getOwnPropertyDescriptors",
	"getOwnPropertyNames",
	"getOwnPropertySymbols",
	"assign",
	"create",
	"defineProperty",
	"defineProperties",
	"entries",
	"is",
	"seal",
	"isSealed",
	"freeze",
	"isFrozen",
	"preventExtensions",
	"isExtensible",
	"toString",
	"toLocaleString",
	"valueOf",
	"hasOwnProperty",
	"isPrototypeOf",
	"propertyIsEnumerable",

	# Regex
	"RegExp",
	"exec",
	
	# Math
	"abs",
	"acos",
	"acosh",
	"asin",
	"asinh",
	"atan",
	"atanh",
	"atan2",
	"cbrt",
	"ceil",
	"clz32",
	"cos",
	"cosh",
	"exp",
	"expm1",
	"floor",
	"fround",
	"hypot",
	"imul",
	"log",
	"log10",
	"log1p",
	"log2",
	"max",
	"min",
	"pow",
	"random",
	"round",
	"sign",
	"sin",
	"sinh",
	"sqrt",
	"tan",
	"tanh",
	"trunc",

    # APIs
    "DOMParser",
    "Notification",
    "Math",
    "Worker",
    "localStorage",
    "sessionStorage",
    "Reflect",
    "FileReader",
    "navigator",
    "constructor",
    "setTimeout",
    "setInterval",
    "console",
    "Promise",
    "eval",
    "Proxy",
    "decodeURIComponent",
    "encodeURIComponent",
    "decodeURI",
    "encodeURI",
    "dataLayer",
    "escape",
    "unescape",
    "isFinite",
    "parseInt",
    "parseFloat",


    # Requests and WebSockets
    "Request",
    "XMLHttpRequest",
    "ActiveXObject",
    "fetch",
    "WebSocket",


    # Events, Signals and Observers
    "AbortSignal",
    "attachEvent",
    "MouseEvent",
    "Touch",
    "TouchEvent",
    "CustomEvent",
    "Event",
    "EventTarget",
    "EventEmitter",
    "EventSource",
    "ResizeObserver",
    "ReportingObserver",
    "IntersectionObserver",
    "PerformanceObserver",
    "MutationObserver",

    # DOM Nodes and Attributes
    "TextDecoder",
    "TextEncoder",
    "Node",
    "Element",
    "HTMLDocument",
    "HTMLElement",
    "HTMLTemplateElement",
    "HTMLIFrameElement",
    "HTMLInputElement",
    "HTMLAnchorElement",
    "HTMLButtonElement",
    "HTMLLinkElement",
    "HTMLImageElement",
    "HTMLEmbedElement",
    "HTMLFrameElement",
    "HTMLObjectElement",
    "HTMLScriptElement",
    "NamedNodeMap",
    "NodeList",
    "SVGRect",
    "MediaSource",

    # CSS
    "CSSRule",
    "CSSStyleDeclaration",
    "CSSStyleSheet",
    "CSSStyleRule",

    # Browsers
    "chrome",
    "safari",
    "firefoxAccessException",

    # Data Types
    "trustedTypes",
    "HTMLCollection",
    "WeakMap",
    "WeakSet",
    "JSON",
    "Symbol",
    "Boolean",
    "Object",
    "String",
    "Array",
    "Image",
    "Number",
    "Function",
    "Map",
    "Date",
    "undefined",
    "null",
    "Float64Array",
    "Float32Array",
    "Uint8ClampedArray",
    "Uint16Array",
    "Uint32Array",
    "Int16Array",
    "Int32Array",
    "Int8Array",
    "Uint8Array",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "Blob",
    "FormData",
    "URLSearchParams",
    "ReferenceError",
    "RangeError",
    "SyntaxError",
    "Error",
    "TypeError",
    "RegExp" ,
    "arguments",
    "globalThis",
    "Infinity",

    # Common Libs
    "importScripts",
    "module",
    "requirejs",
    "require",
    "jQuery",
    "jQuery",
    "_jQuery",
    "$",
    "self",
    "define",

    # Functions
    "apply",
    "call",
    "bind",

    # Arrays         
    "concat",    
    "copyWithin",
    "entries",   
    "every",     
    "fill",      
    "filter",    
    "find",      
    "findIndex", 
    "forEach",   
    "from",      
    "includes",  
    "indexOf",   
    "isArray",   
    "join",      
    "keys",      
    "lastIndexOf",
    "map",       
    "pop",       
    "push",      
    "reduce",    
    "reduceRight",
    "reverse",   
    "shift",     
    "slice",     
    "some",      
    "sort",      
    "splice",    
    "toString",  
    "unshift",   
    "valueOf",   

    # Boolean
    "toString",  
    "valueOf", 

    # Classes
    "extends",
    "super",
    "static",

    # Date
    "getDate",
    "getDay",
    "getFullYear",
    "getHours",
    "getMilliseconds",
    "getMinutes",
    "getMonth",
    "getSeconds",
    "getTime",
    "getTimezoneOffset",
    "getUTCDate",
    "getUTCDay",
    "getUTCFullYear",
    "getUTCHours",
    "getUTCMilliseconds",
    "getUTCMinutes",
    "getUTCMonth",
    "getUTCSeconds",
    "getYear",
    "now",
    "parse",
    "setDate",
    "setFullYear",
    "setHours",
    "setMilliseconds",
    "setMinutes",
    "setMonth",
    "setSeconds",
    "setTime",
    "setUTCDate",
    "setUTCFullYear",
    "setUTCHours",
    "setUTCMilliseconds",
    "setUTCMinutes",
    "setUTCMonth",
    "setUTCSeconds",
    "setYear",
    "toDateString",
    "toGMTString",
    "toISOString",
    "toJSON",
    "toLocaleDateString",
    "toLocaleTimeString",
    "toLocaleString",
    "toString",
    "toTimeString",
    "toUTCString",
    "UTC",
    "valueOf",

    # JSON
    "parse",
    "stringify",

    # MATH
    "abs",
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "cbrt",
    "ceil",
    "clz32",
    "cos  ",
    "cosh",
    "exp",
    "expm1",
    "floor",
    "fround",
    "log",
    "log10",
    "log1p",
    "log2",
    "max",
    "min",
    "pow",
    "random",
    "round",
    "sign ",
    "sin  ",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "trunc",

    # Number
    "isFinite",
    "isInteger",
    "isNaN",
    "isSafeInteger",
    "toExponential",
    "toFixed",
    "toLocaleString",
    "toPrecision",
    "toString",
    "valueOf",

    # RegExp
    "compile",

    # String
    "charAt",
    "charCodeAt",
    "concat",
    "endsWith",
    "fromCharCode",
    "includes",
    "indexOf",
    "lastIndexOf",
    "localeCompare",
    "match",
    "repeat",
    "replace",
    "search",
    "slice",
    "split",
    "startsWith",
    "substr",
    "substring",
    "toLocaleLowerCase",
    "toLocaleUpperCase",
    "toLowerCase",
    "toString",
    "toUpperCase",
    "trim",
    "valueOf",
]))
